# Generated by Django 4.2.1 on 2023-05-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image_url',
            new_name='image',
        ),
    ]
